Wrap environment resume to handle exit code in CI env (#1182)
* Scheduled CI task to keep alive defined development environments

* Refine to handle non-0 exit code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -302,6 +302,14 @@ jobs:
               platform environment:resume -p $PLATFORM_PROJECT -e $env -y
             done
 
+            exit_code=$?
+            # Adjust exit code to 0 if non-zero
+            if [ $exit_code -ne 0 ]; then
+              echo "Environment resume command exited with non-zero exit code, catching to avoid false error on CI task"
+              exit_code=0
+            fi
+            exit $exit_code
+
 workflows:
   version: 2
   # Our default pipeline that tests the integrity of our code.
